# Generated by Django 4.1.7 on 2023-09-27 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('cycle', models.CharField(max_length=100)),
                ('ht', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hl', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Fall', 'Fall')], max_length=20)),
                ('headquarters', models.CharField(choices=[('Headquarters A', 'Headquarters A'), ('Headquarters B', 'Headquarters B'), ('Headquarters C', 'Headquarters C')], max_length=20)),
                ('cycle', models.CharField(choices=[('Cycle 1', 'Cycle 1'), ('Cycle 2', 'Cycle 2'), ('Cycle 3', 'Cycle 3')], max_length=20)),
                ('section', models.CharField(max_length=1)),
                ('career', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('hours', models.IntegerField()),
                ('classroom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('surname_and_names', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Does not register', 'Does not register'), ('Masters', 'Masters'), ('Doctors', 'Doctors')], max_length=20)),
                ('type', models.CharField(choices=[('Contracted', 'Contracted'), ('Main', 'Main')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('income', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('type_of_research', models.CharField(max_length=100)),
                ('research_line', models.CharField(max_length=100)),
                ('sub_line', models.CharField(max_length=100)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('course_model', models.ManyToManyField(to='dashboard.teacher')),
            ],
        ),
    ]
