# Generated by Django 4.1.7 on 2023-08-30 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('cycle', models.CharField(max_length=100)),
                ('ht', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('hl', models.IntegerField()),
            ],
        ),
    ]
