# Generated by Django 4.1.7 on 2023-09-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('surname_and_names', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Does not register', 'Does not register'), ('Masters', 'Masters'), ('Doctors', 'Doctors')], max_length=20)),
                ('manager', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Contracted', 'Contracted'), ('Main', 'Main')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
